# Generated by Django 4.2 on 2024-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gr_construction_web', '0003_bill_worksite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksite',
            old_name='final_shot',
            new_name='finished_image',
        ),
    ]
